In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_excel(r"C:\Users\AGALYAMAHESWARAN\Desktop\Documents\Call_center_Performance_Analysis_System\Datasets\call_center1.xlsx")

Entire Table

In [4]:
df.head()

,Unnamed: 0,Call Centre Data,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating,NaN,NaN,NaN,Customer ID,Gedner,Age,City
2,NaN,Call_7271,C0003,116,R05,2023-01-01 00:00:00,128,4.9,NaN,NaN,NaN,C0001,Male,41,Columbus
3,NaN,Call_7272,C0004,119,R05,2023-01-01 00:00:00,135,2.9,NaN,NaN,NaN,C0002,Male,31,Cleveland
4,NaN,Call_7273,C0005,68,R02,2023-01-01 00:00:00,66,4.7,NaN,NaN,NaN,C0003,Male,26,Cincinnati

Calls Table

In [9]:
calls=pd.read_excel(r"C:\Users\AGALYAMAHESWARAN\Desktop\Documents\Call_center_Performance_Analysis_System\Datasets\call_center1.xlsx",header=2,usecols="B:H")

In [10]:
calls.head()

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
0,Call_7271,C0003,116,R05,2023-01-01,128,4.9
1,Call_7272,C0004,119,R05,2023-01-01,135,2.9
2,Call_7273,C0005,68,R02,2023-01-01,66,4.7
3,Call_7274,C0014,119,R02,2023-01-01,22,2.9
4,Call_7275,C0011,128,R01,2023-01-02,31,2.8

Customers Table

In [5]:
customers=pd.read_excel(r"C:\Users\AGALYAMAHESWARAN\Desktop\Documents\Call_center_Performance_Analysis_System\Datasets\call_center1.xlsx",header=2,usecols="L:O",nrows=15)

In [21]:
customers

   Customer ID.1  Gedner  Age        City
0          C0001    Male   41    Columbus
1          C0002    Male   31   Cleveland
2          C0003    Male   26  Cincinnati
3          C0004    Male   36  Cincinnati
4          C0005    Male   37    Columbus
5          C0006    Male   23    Columbus
6          C0007  Female   22   Cleveland
7          C0008  Female   42   Cleveland
8          C0009  Female   25    Columbus
9          C0010  Female   30   Cleveland
10         C0011  Female   30  Cincinnati
11         C0012  Female   28  Cincinnati
12         C0013  Female   37   Cleveland
13         C0014  Female   38    Columbus
14         C0015  Female   43   Cleveland

In [22]:
calls.tail()

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
995,Call_8266,C0002,81,R05,2023-12-30,28,3.9
996,Call_8267,C0007,127,R04,2023-12-30,215,3.8
997,Call_8268,C0013,146,R05,2023-12-31,115,2.3
998,Call_8269,C0010,123,R05,2023-12-31,64,3.7
999,Call_8270,C0009,114,R01,2023-12-31,40,3.9

In [24]:
customers.head()

  Customer ID.1 Gedner  Age        City
0         C0001   Male   41    Columbus
1         C0002   Male   31   Cleveland
2         C0003   Male   26  Cincinnati
3         C0004   Male   36  Cincinnati
4         C0005   Male   37    Columbus

In [23]:
customers.tail()

   Customer ID.1  Gedner  Age        City
10         C0011  Female   30  Cincinnati
11         C0012  Female   28  Cincinnati
12         C0013  Female   37   Cleveland
13         C0014  Female   38    Columbus
14         C0015  Female   43   Cleveland

In [17]:
calls.sample(10)

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
907,Call_8178,C0003,95,R02,2023-11-10,140,3.9
674,Call_7945,C0007,61,R01,2023-08-19,93,2.7
718,Call_7989,C0001,36,R03,2023-09-09,152,4.3
171,Call_7442,C0010,40,R03,2023-03-05,92,4.7
836,Call_8107,C0007,77,R02,2023-10-15,78,3.9
354,Call_7625,C0005,91,R02,2023-04-14,84,4.5
322,Call_7593,C0001,150,R05,2023-04-07,24,3.8
60,Call_7331,C0013,74,R01,2023-01-24,66,4.0
730,Call_8001,C0003,110,R03,2023-09-13,180,4.2
973,Call_8244,C0015,126,R04,2023-12-16,185,4.8

In [26]:
customers.sample(10)

   Customer ID.1  Gedner  Age        City
1          C0002    Male   31   Cleveland
2          C0003    Male   26  Cincinnati
11         C0012  Female   28  Cincinnati
9          C0010  Female   30   Cleveland
6          C0007  Female   22   Cleveland
13         C0014  Female   38    Columbus
12         C0013  Female   37   Cleveland
4          C0005    Male   37    Columbus
3          C0004    Male   36  Cincinnati
10         C0011  Female   30  Cincinnati

In [28]:
type(calls)

pandas.DataFrame

shape=variable

In [29]:
calls.shape

(1000, 7)

In [30]:
calls.columns

Index(['Call number', 'Customer ID', 'Duration', 'Representative',
       'Date of Call', 'Purchase Amount', 'Satisfaction Rating'],
      dtype='str')

To Know the datatype in entire table

In [31]:
calls.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Call number          1000 non-null   str
 1   Customer ID          1000 non-null   str
 2   Duration             1000 non-null   int64
 3   Representative       1000 non-null   str
 4   Date of Call         1000 non-null   datetime64[us]
 5   Purchase Amount      1000 non-null   int64
 6   Satisfaction Rating  1000 non-null   float64
dtypes: datetime64[us](1), float64(1), int64(2), str(3)
memory usage: 54.8 KB

In [7]:
calls.describe()

,Duration,Date of Call,Purchase Amount,Satisfaction Rating
count,1000.000000,1000,1000.000000,1000.000000
mean,89.850000,2023-06-15 00:34:33.600000,96.623000,3.885400
min,2.000000,2023-01-01 00:00:00,20.000000,0.000000
25%,62.000000,2023-03-20 00:00:00,50.000000,3.400000
50%,89.000000,2023-05-25 12:00:00,88.000000,4.000000
75%,119.000000,2023-09-24 00:00:00,130.000000,4.500000
max,176.000000,2023-12-31 00:00:00,225.000000,5.000000
std,37.626736,NaN,52.465794,0.835551

Questions:
Total calls
Peak Month,busy day
Best Representatives
avg duration of calls
purchase amount-high,avg
Age and city wise analysis

In [10]:
calls.isnull().sum()

Call number            0
Customer ID            0
Duration               2
Representative         0
Date of Call           0
Purchase Amount        2
Satisfaction Rating    5
dtype: int64

In [8]:
customers.isnull().sum()

Customer ID.1    0
Gedner           0
Age              0
City             0
dtype: int64

It shows which rows contains null value ,if it contains it display true or false:

In [13]:
calls.isnull().any(axis=1)

0      False
1      False
2       True
3       True
4       True
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [12]:
calls.isnull().all()

Call number            False
Customer ID            False
Duration               False
Representative         False
Date of Call           False
Purchase Amount        False
Satisfaction Rating    False
dtype: bool

In [14]:
calls[calls.isnull().any(axis=1)]

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
2,Call_7273,C0005,68.0,R02,2023-01-01,NaN,NaN
3,Call_7274,C0014,119.0,R02,2023-01-01,22.0,NaN
4,Call_7275,C0011,128.0,R01,2023-01-02,31.0,NaN
5,Call_7276,C0011,NaN,R02,2023-01-03,135.0,NaN
6,Call_7277,C0007,84.0,R05,2023-01-03,NaN,NaN
11,Call_7282,C0013,NaN,R05,2023-01-03,46.0,3.4

To fill missing values:

In [20]:
calls["Purchase Amount"]=calls["Purchase Amount"].fillna(calls["Purchase Amount"].mean(),inplace=True)

C:\Users\AGALYAMAHESWARAN\AppData\Local\Temp\ipykernel_3360\1744965682.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  calls["Purchase Amount"]=calls["Purchase Amount"].fillna(calls["Purchase Amount"].mean(),inplace=True)

In [25]:
calls.isnull().sum()

Call number            0
Customer ID            0
Duration               0
Representative         0
Date of Call           0
Purchase Amount        0
Satisfaction Rating    0
dtype: int64

In [22]:
calls["Duration"]=calls["Duration"].fillna(calls["Duration"].mean(),inplace=True)

C:\Users\AGALYAMAHESWARAN\AppData\Local\Temp\ipykernel_3360\2727262099.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  calls["Duration"]=calls["Duration"].fillna(calls["Duration"].mean(),inplace=True)

In [24]:
calls["Satisfaction Rating"]=calls["Satisfaction Rating"].fillna(calls["Satisfaction Rating"].mean(),inplace=True)

C:\Users\AGALYAMAHESWARAN\AppData\Local\Temp\ipykernel_3360\1235390652.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  calls["Satisfaction Rating"]=calls["Satisfaction Rating"].fillna(calls["Satisfaction Rating"].mean(),inplace=True)

To fill missing names:

In [ ]:
calls["Representative"]=calls["Representative"].fillna("Unknown",inplace=True)

In [26]:
calls.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Call number          1000 non-null   str
 1   Customer ID          1000 non-null   str
 2   Duration             1000 non-null   float64
 3   Representative       1000 non-null   str
 4   Date of Call         1000 non-null   datetime64[us]
 5   Purchase Amount      1000 non-null   float64
 6   Satisfaction Rating  1000 non-null   float64
dtypes: datetime64[us](1), float64(3), str(3)
memory usage: 54.8 KB

To check Duplicates:

In [ ]:
calls.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

To count duplicates:

In [28]:
calls.duplicated().sum()

np.int64(0)

To remove Duplicates:

axis=1:Row   |  axis=0=Column

In [31]:
calls.drop_duplicates().all(axis=1).sum()

np.int64(999)

To know which contains duplicates,here there is no duplicates so it showing only header:

In [ ]:
calls[calls.duplicated()]

Empty DataFrame
Columns: [Call number, Customer ID, Duration, Representative, Date of Call, Purchase Amount, Satisfaction Rating]
Index: []

In [35]:
calls.drop_duplicates(inplace=True)

To change into datetime:

In [37]:
calls["Date of Call"]=pd.to_datetime(calls["Date of Call"])

In [52]:
calls.dtypes

Call number                       str
Customer ID                       str
Duration                      float64
Representative                    str
Date of Call           datetime64[us]
Purchase                      float64
Satisfaction Rating           float64
dtype: object

In [56]:
calls.columns

Index(['Call number', 'Customer ID', 'Duration', 'Representative',
       'Date of Call', 'Purchase', 'Rating'],
      dtype='str')

To Renaming Columns:

In [55]:
calls.rename(columns={"Purchase Amount":"Purchase","Satisfaction Rating":"Rating"},inplace=True)

In [42]:
calls.to_csv("Cleaned_Data.csv",index=False)

Data Frame is a collection of rows and columns(2D)

Single column stores as series

In [44]:
type(calls["Customer ID"])

pandas.Series

In [58]:
calls[["Purchase","Representative","Rating"]]

       Purchase Representative    Rating
0    128.000000            R05  4.900000
1    135.000000            R05  2.900000
2     96.690381            R02  3.884925
3     22.000000            R02  3.884925
4     31.000000            R01  3.884925
..          ...            ...       ...
995   28.000000            R05  3.900000
996  215.000000            R04  3.800000
997  115.000000            R05  2.300000
998   64.000000            R05  3.700000
999   40.000000            R01  3.900000

[1000 rows x 3 columns]

In [59]:
calls.Rating[calls.Rating<3]

1      2.9
9      2.9
23     2.1
28     2.9
35     2.4
      ...
979    2.1
980    2.8
983    1.7
993    2.9
997    2.3
Name: Rating, Length: 143, dtype: float64

In [61]:
calls.Rating.sort_values(ascending=False)

547    5.0
20     5.0
39     5.0
506    5.0
759    5.0
      ...
128    1.0
557    0.9
180    0.7
445    0.7
69     0.0
Name: Rating, Length: 1000, dtype: float64

In [62]:
calls.Representative.unique()

<StringArray>
['R05', 'R02', 'R01', 'R04', 'R03']
Length: 5, dtype: str

In [65]:
customers.City.unique()

<StringArray>
['Columbus', 'Cleveland', 'Cincinnati']
Length: 3, dtype: str

In [68]:
calls.Representative.value_counts()

Representative
R02    218
R03    207
R05    200
R01    189
R04    186
Name: count, dtype: int64

In [72]:
rep_counts=calls.Representative.value_counts()
print(rep_counts.max())

218

In [75]:
print(calls.groupby("Representative")["Rating"].mean())

Representative
R01    3.928492
R02    3.867224
R03    3.858937
R04    3.897312
R05    3.878425
Name: Rating, dtype: float64

In [ ]:
highest_calls=calls.groupby("Representative")["Call number"].count()
highest_calls.max()

np.int64(218)

In [82]:
merged_table=pd.merge(calls,customers,left_on="Customer ID",right_on="Customer ID.1")
print(merged_table)

    Call number Customer ID  Duration Representative Date of Call    Purchase  \
0     Call_7271       C0003     116.0            R05   2023-01-01  128.000000
1     Call_7272       C0004     119.0            R05   2023-01-01  135.000000
2     Call_7273       C0005      68.0            R02   2023-01-01   96.690381
3     Call_7274       C0014     119.0            R02   2023-01-01   22.000000
4     Call_7275       C0011     128.0            R01   2023-01-02   31.000000
..          ...         ...       ...            ...          ...         ...
995   Call_8266       C0002      81.0            R05   2023-12-30   28.000000
996   Call_8267       C0007     127.0            R04   2023-12-30  215.000000
997   Call_8268       C0013     146.0            R05   2023-12-31  115.000000
998   Call_8269       C0010     123.0            R05   2023-12-31   64.000000
999   Call_8270       C0009     114.0            R01   2023-12-31   40.000000

       Rating Customer ID.1  Gedner  Age        City
0    4.900000         C0003    Male   26  Cincinnati
1    2.900000         C0004    Male   36  Cincinnati
2    3.884925         C0005    Male   37    Columbus
3    3.884925         C0014  Female   38    Columbus
4    3.884925         C0011  Female   30  Cincinnati
..        ...           ...     ...  ...         ...
995  3.900000         C0002    Male   31   Cleveland
996  3.800000         C0007  Female   22   Cleveland
997  2.300000         C0013  Female   37   Cleveland
998  3.700000         C0010  Female   30   Cleveland
999  3.900000         C0009  Female   25    Columbus

[1000 rows x 11 columns]

In [83]:
calls.dtypes
customers.dtypes

Customer ID.1      str
Gedner             str
Age              int64
City               str
dtype: object

In [87]:
merged_table.groupby("City")["Purchase"].sum()

City
Cincinnati    26061.000000
Cleveland     37885.690381
Columbus      32743.690381
Name: Purchase, dtype: float64